TSERV-2581: Update JDK version and release process

diff --git a/.github/workflows/R01-plugin-release.yml b/.github/workflows/R01-plugin-release.yml
--- a/.github/workflows/R01-plugin-release.yml
+++ b/.github/workflows/R01-plugin-release.yml
@@ -19,11 +19,11 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Set up JDK 11
+      - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           distribution: temurin
-          java-version: '11'
+          java-version: '17'
           server-id: central
           server-username: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
           server-password: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
@@ -38,6 +38,19 @@ jobs:
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+      - name: Create release branch
+        run: |
+          VERSION=${{ github.event.inputs.version }}
+          RELEASE_BRANCH=release/$VERSION
+          
+          git ls-remote --exit-code --heads origin $RELEASE_BRANCH && {
+            echo "ERROR: $RELEASE_BRANCH already exists"
+            exit 1
+          }
+
+          git checkout -b $RELEASE_BRANCH
+          git push -u origin $RELEASE_BRANCH
 
       - name: Set release version
         run: |
@@ -60,30 +73,7 @@ jobs:
       - name: Create and push tag
         run: |
           git tag v${{ github.event.inputs.version }}
-          git push origin HEAD
+          git push origin release/${{ github.event.inputs.version }}
           git push origin v${{ github.event.inputs.version }}
 
-      - name: Calculate next snapshot version
-        id: next_version
-        run: |
-          VERSION=${{ github.event.inputs.version }}
-
-          MAJOR=$(echo $VERSION | cut -d. -f1)
-          MINOR=$(echo $VERSION | cut -d. -f2)
-          PATCH=$(echo $VERSION | cut -d. -f3)
-
-          NEXT_PATCH=$((PATCH + 1))
-
-          echo "version=${MAJOR}.${MINOR}.${NEXT_PATCH}-SNAPSHOT" >> $GITHUB_OUTPUT
-
-      - name: Set next snapshot version
-        run: |
-          mvn -B versions:set \
-            -DnewVersion=${{ steps.next_version.outputs.version }} \
-            -DgenerateBackupPoms=false
-
-      - name: Commit next snapshot version
-        run: |
-          git add pom.xml
-          git commit -m "Prepare for next development iteration ${{ steps.next_version.outputs.version }}"
-          git push origin HEAD
+      
